---
title: "Working with false color images"
author: "Rachel Swick"
format: html
editor: visual
---

# Working with False Color Images

```{r}
# Load libraries
library(tidyverse)
library(sf)
library(terra)
```

```{r}
# Set directory for folder
pre_fire_dir <- here::here("data", "LC80340322016189-SC20170128091153")

# Create a list of all images that have the extension .tif and contain the word band
pre_fire_bands <- list.files(pre_fire_dir,
                             pattern = glob2rx("*band*.tif$"),
                             full.names = TRUE)
# Create a raster stack
pre_fire_rast <- rast(pre_fire_bands)

# Read mask raster
pre_mask <- rast(here::here("data", "LC80340322016189-SC20170128091153", "LC80340322016189LGN00_cfmask_crop.tif"))
```

```{r}
# Set directory for folder
post_fire_dir <- here::here("data", "LC80340322016205-SC20170127160728")

# Create a list of all images that have the extension .tif and contain the word band
post_fire_bands <- list.files(post_fire_dir,
                             pattern = glob2rx("*band*.tif$"),
                             full.names = TRUE)
# Create a raster stack
post_fire_rast <- rast(post_fire_bands)

# Read mask raster
post_mask <- rast(here::here("data", "LC80340322016189-SC20170128091153", "LC80340322016189LGN00_cfmask_crop.tif"))
```

```{r}
# rename bands
bands <- c("Aerosol", "Blue", "Green", "Red", "NIR", "SWIR1", "SWIR2")
names(pre_fire_rast) <- bands
names(post_fire_rast) <- bands
```

```{r}
# mask clouds and shadows
# Set all cells with values greater than 0 to NA
pre_mask[pre_mask > 0] <- NA

# Subset raster based on mask
pre_fire_rast <- mask(pre_fire_rast, mask = pre_mask)

# View raster
plot(pre_fire_rast)
```

```{r}
# Set all cells with values greater than 0 to NA
post_mask[post_mask > 0] <- NA

# Subset raster based on mask
post_fire_rast <- mask(post_fire_rast, mask = post_mask)

# View raster
plot(post_fire_rast)
```
































